# Collect all compiler IDs
set(C_COMPILER_ID "${CMAKE_C_COMPILER_ID}")
set(CXX_COMPILER_ID "${CMAKE_CXX_COMPILER_ID}")
set(FORTRAN_COMPILER_ID "${CMAKE_Fortran_COMPILER_ID}")

# Define a unified suffix
if(C_COMPILER_ID STREQUAL "GNU" AND CXX_COMPILER_ID STREQUAL "GNU" AND FORTRAN_COMPILER_ID STREQUAL "GNU")
    set(COMPILER_SUFFIX "GNU")
elseif(C_COMPILER_ID STREQUAL "Intel" AND CXX_COMPILER_ID STREQUAL "Intel" AND FORTRAN_COMPILER_ID STREQUAL "Intel")
    set(COMPILER_SUFFIX "Intel")
elseif(C_COMPILER_ID STREQUAL "Clang" AND CXX_COMPILER_ID STREQUAL "Clang")
    # For example, using Clang + Flang or Clang + GFortran
    set(COMPILER_SUFFIX "ClangMixed")
else()
    # Fallback: concatenate the three IDs
    set(COMPILER_SUFFIX "${C_COMPILER_ID}-${CXX_COMPILER_ID}-${FORTRAN_COMPILER_ID}")
endif()