name: Version Bump and Tag

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make the script executable
        run: chmod +x ./script/version_bump.sh

      - name: Determine the version bump type
        id: get_bump_type
        run: |
          # Get the commit messages from the last push
          commits=$(git log -1 --pretty=%B)

          echo "Commit messages: $commits"

          # Determine the bump type based on commit message
          if echo "$commits" | grep -q "MAJOR:"; then
            echo "Bump type: major"
            echo "::set-output name=bump_type::major"
          elif echo "$commits" | grep -q "MINOR:"; then
            echo "Bump type: minor"
            echo "::set-output name=bump_type::minor"
          else
            echo "Bump type: patch"
            echo "::set-output name=bump_type::patch"
          fi

      - name: Run version bump script
        run: ./scripts/version_bump.sh --${{ steps.get_bump_type.outputs.bump_type }}

      - name: Push changes and tags
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add scripts/version.txt
          git commit -m "Bump version to $(cat script/version.txt) via GitHub Actions"
          git tag "v$(cat script/version.txt)"
          git push origin main --tags
